apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: uat
  name: pocweb-deployment
spec:
  selector:
    matchLabels:
      app: pocweb-pod
  replicas: 1
  template:
    metadata:
      name: pocweb
      labels:
        app: pocweb-pod
    spec:
      containers:
      - name: pocweb-container
        image: ubuntu/poc:web
        ports:
        - containerPort: 8080
