apiVersion: v1
kind: Service
metadata:
  namespace: local
  name: pocweb-service
spec:
  type: NodePort
  selector:
    app: pocweb-pod
  ports:
    #外部訪問的port
    nodePort: 8080
    #內部訪問的port
    port: 8080
    #pod的port
    targetPort: 8080
